spring.application.name=WIKIKNOWLedge
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html
spring.thymeleaf.cache=false

spring.data.mongodb.uri=mongodb://localhost:27017/wikiknowledge

server.port=8080
